image:
  repository: "958124171439.dkr.ecr.ap-south-1.amazonaws.com/example-app"
  tag: "REPLACED_BY_CI" # app CI overwrites this line with the built commit SHA

replicaCount: 1
autoscaling:
  enabled: false
