name: bump-gitops-image

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

      app_name:
        required: true
        type: string

      image_tag:
        required: true
        type: string

      auto_merge:
        required: false
        type: boolean
        default: false

    secrets:
      GITOPS_REPO_TOKEN:
        required: true

jobs:
  bump:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout platform-cicd
        uses: actions/checkout@v4
        with:
          repository: indiraselvam/platform-cicd
          token: ${{ secrets.GITOPS_REPO_TOKEN }}
          path: platform-cicd

      - name: Bump image.tag
        working-directory: platform-cicd
        run: |
          FILE="charts/${{ inputs.app_name }}/values-${{ inputs.environment }}.yaml"

          echo "Updating $FILE"

          yq -i '.image.tag = "${{ inputs.image_tag }}"' "$FILE"

          echo "Updated values file:"
          cat "$FILE"

      - name: Open PR
        working-directory: platform-cicd
        env:
          GH_TOKEN: ${{ secrets.GITOPS_REPO_TOKEN }}
        run: |
          BRANCH="bump/${{ inputs.app_name }}-${{ inputs.environment }}-${{ inputs.image_tag }}"

          git checkout -b "$BRANCH"

          git config user.name "gitops-bot"
          git config user.email "gitops-bot@users.noreply.github.com"

          git add "charts/${{ inputs.app_name }}/values-${{ inputs.environment }}.yaml"

          git commit -m "deploy(${{ inputs.app_name }}/${{ inputs.environment }}): ${{ inputs.image_tag }}"

          git push origin "$BRANCH"

          gh pr create \
            --title "deploy(${{ inputs.app_name }}/${{ inputs.environment }}): ${{ inputs.image_tag }}" \
            --body "Automated image bump from ${{ github.repository }}@${{ github.sha }}" \
            --base main \
            --head "$BRANCH"

      - name: Auto-merge dev
        if: inputs.auto_merge
        working-directory: platform-cicd
        env:
          GH_TOKEN: ${{ secrets.GITOPS_REPO_TOKEN }}
        run: |
          BRANCH="bump/${{ inputs.app_name }}-${{ inputs.environment }}-${{ inputs.image_tag }}"

          gh pr merge "$BRANCH" --squash --auto
